[2024-06-05T16:36:11.298+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:36:11.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T16:36:11.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_postgres.download_and_insert_data manual__2024-06-05T16:35:59.651756+00:00 [queued]>
[2024-06-05T16:36:11.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T16:36:11.413+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_insert_data> on 2024-06-05 16:35:59.651756+00:00
[2024-06-05T16:36:11.428+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:36:11.439+0000] {standard_task_runner.py:63} INFO - Started process 69 to run task
[2024-06-05T16:36:11.451+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_postgres', 'download_and_insert_data', 'manual__2024-06-05T16:35:59.651756+00:00', '--job-id', '703', '--raw', '--subdir', 'DAGS_FOLDER/pipe.py', '--cfg-path', '/tmp/tmph7i0f492']
[2024-06-05T16:36:11.458+0000] {standard_task_runner.py:91} INFO - Job 703: Subtask download_and_insert_data
[2024-06-05T16:36:11.704+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_postgres.download_and_insert_data manual__2024-06-05T16:35:59.651756+00:00 [running]> on host 3ca4815e3382
[2024-06-05T16:36:11.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_postgres' AIRFLOW_CTX_TASK_ID='download_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T16:35:59.651756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T16:35:59.651756+00:00'
[2024-06-05T16:36:11.891+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:36:15.638+0000] {python.py:237} INFO - Done. Returned value was: /tmp/data_1000.csv
[2024-06-05T16:36:15.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:36:15.691+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_postgres, task_id=download_and_insert_data, run_id=manual__2024-06-05T16:35:59.651756+00:00, execution_date=20240605T163559, start_date=20240605T163611, end_date=20240605T163615
[2024-06-05T16:36:15.739+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T16:36:15.784+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:36:15.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
